# Generated by Django 4.0.5 on 2022-06-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0005_producto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
