# Generated by Django 4.0.5 on 2022-07-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='test@test.com', max_length=20, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
