# Generated by Django 4.0.5 on 2022-07-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0010_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=11, verbose_name='Telefono'),
        ),
    ]
