# Generated by Django 4.0.5 on 2022-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0011_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Carro')),
                ('id_producto', models.CharField(max_length=5, verbose_name='Id Producto')),
                ('nombreproducto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('total', models.CharField(max_length=10, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('total', models.CharField(max_length=10, verbose_name='Total')),
                ('estado', models.CharField(default='Procesando Compra', max_length=30, verbose_name='Estado')),
            ],
        ),
    ]
