# Generated by Django 4.0.5 on 2022-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0016_rename_imagen_producto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(max_length=30, verbose_name='Estado'),
        ),
    ]
