# Generated by Django 4.0.5 on 2022-07-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0017_alter_compra_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
