# Generated by Django 4.0.5 on 2022-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HildaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Id')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('nombre_producto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('precio', models.CharField(max_length=10, verbose_name='Precio')),
            ],
        ),
    ]
